package edu.pitt.cs;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.time.Duration;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        driver = new ChromeDriver(options);

        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void tEST1LINKS() {
        String baseUrl = "http://localhost:8080";
        driver.get(baseUrl + "//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        {
            WebElement element = driver.findElement(By.linkText("Reset"));
            String attribute = element.getAttribute("href");
            vars.put("resetLink", attribute);
        }
        assertEquals(baseUrl + "/reset", vars.get("resetLink").toString());
        driver.close();
    }

    @Test
    public void tEST2RESET() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Reset")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(),
                is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        driver.close();
    }

    @Test
    public void tEST3CATALOG() {
        String baseUrl = "http://localhost:8080";
        driver.get(baseUrl + "//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Catalog")).click();
        {
            WebElement element = driver.findElement(By.xpath("//img[@alt=\'Old Deuteronomy\']"));
            String attribute = element.getAttribute("src");
            vars.put("src", attribute);
        }
        assertEquals(baseUrl + "/images/cat2.jpg", vars.get("src").toString());
        driver.close();
    }

    @Test
    public void tEST4LISTING() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Catalog")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"listing\"]/ul/li[1]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"listing\"]/ul/li[2]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"listing\"]/ul/li[3]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"listing\"]/ul/li[4]"));
            assert (elements.size() == 0);
        }
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        driver.close();
    }

    @Test
    public void tEST5RENTACAT() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Rent-A-Cat")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(),\'Rent\')]"));
            assert (elements.size() > 0);
        }
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(),\'Return\')]"));
            assert (elements.size() > 0);
        }
        driver.close();
    }

    @Test
    public void tEST6RENT() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Rent-A-Cat")).click();
        driver.findElement(By.id("rentID")).click();
        driver.findElement(By.id("rentID")).sendKeys("1");
        driver.findElement(By.xpath("//button[contains(text(),\'Rent\')]")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("Rented out"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(),
                is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"rentResult\"]")).getText(), is("Success!"));
        driver.close();
    }

    @Test
    public void tEST7RETURN() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
        driver.manage().window().setSize(new Dimension(1200, 800));
        driver.findElement(By.linkText("Rent-A-Cat")).click();
        driver.findElement(By.id("returnID")).click();
        driver.findElement(By.id("returnID")).sendKeys("2");
        driver.findElement(By.xpath("//button[contains(text(),\'Return\')]")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(),
                is("ID 2. Old Deuteronomy"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
        assertThat(driver.findElement(By.xpath("//*[@id=\"returnResult\"]")).getText(), is("Success!"));
        driver.close();
    }

    @Test
    public void tEST8FEEDACAT() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.findElement(By.linkText("Feed-A-Cat")).click();
        {
            List<WebElement> elements = driver.findElements(By.xpath("//button[contains(text(),\'Feed\')]"));
            assert (elements.size() > 0);
        }
        driver.close();
    }

    @Test
    public void tEST9FEED() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.findElement(By.linkText("Feed-A-Cat")).click();
        driver.findElement(By.id("catnips")).click();
        driver.findElement(By.id("catnips")).sendKeys("6");
        driver.findElement(By.xpath("//button[contains(text(),\'Feed\')]")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"feedResult\"]")).getText(), is("Nom, nom, nom."));
        driver.close();
    }

    @Test
    public void tEST10GREETACAT() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.findElement(By.linkText("Greet-A-Cat")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"greeting\"]")).getText(), is("Meow!Meow!Meow!"));
        driver.close();
    }

    @Test
    public void tEST11GREETACATWITHNAME() {
        driver.get("http://localhost:8080//");
        js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
        driver.get("http://localhost:8080//greet-a-cat/Jennyanydots");
        assertThat(driver.findElement(By.xpath("//*[@id=\"greeting\"]")).getText(), is("Meow! from Jennyanydots."));
        driver.close();
    }
}
